"use client";

import { downloadPdf, type PdfLine } from "@/lib/fs/report-pdf";
import { fileSize, type ResidentDocument } from "@/lib/res/documents-data";
import { longDate } from "@/lib/res/format";
import { residentUnit } from "@/lib/res/resident";

/**
 * Hands the resident a file for a document row.
 *
 * There are no real deeds or receipts behind this build, so rather than a dead
 * button or a download that never arrives, each row emits a genuine one-page
 * PDF that says plainly what it stands in for. Written through the same
 * hand-rolled writer the field reports use — no library, nothing fetched.
 */
export function downloadDocument(document: ResidentDocument) {
  const lines: PdfLine[] = [
    { text: "Azentra · Sunrise Residence", size: 10 },
    { text: document.name, size: 20, bold: true, gap: 14 },
    { text: document.category, size: 11, gap: 6 },
    {
      text: `Unit ${residentUnit.number}, ${residentUnit.building}`,
      size: 11,
      gap: 2,
    },
    { text: `Dated ${longDate(document.date)}`, size: 11, gap: 2 },
    {
      text: `${fileSize(document.bytes)} · ${document.type}`,
      size: 11,
      gap: 2,
    },
    { text: "Placeholder", size: 13, bold: true, gap: 26 },
    {
      text: "This document is a stand-in generated by the Azentra demo.",
      size: 11,
      gap: 8,
    },
    {
      text: "No file is stored on a server and nothing here is a legal record.",
      size: 11,
      gap: 4,
    },
  ];

  downloadPdf(`${document.name}.pdf`, lines);
}
